config/routes.rb
Bluebird::Application.routes.draw do
  devise_for :users

   root :to => 'home#index'

  devise_for :users

  match 'read/:category_slug' => 'home#read', :as => "read_category"

  namespace :admin do
    root :to => "dashboard#index"
    resources :categories, :only => [:new, :create, :edit, :update, :destroy, :index]
    resources :sources
    resources :articles, :only => [:edit, :update, :destroy, :index]
    resources :users, :only => [:new, :create, :edit, :update, :destroy, :index]
  end

end

app/models/source.rb
class Source < ActiveRecord::Base

  attr_accessible :screen_name, :name, :active, :category, :category_id, :twitter_id,
                  :location, :description, :url, :date_registration, :lang, :profile_image_url

  belongs_to :category
  has_many :twits
  has_many :articles

  validates_uniqueness_of :screen_name
  validates_presence_of :screen_name
  validates_presence_of :category

  scope :active, where(:active => true)

  before_save :get_twitter_profile

  delegate :name, :to => :category, :prefix => true

  private
  def get_twitter_profile
    unless screen_name_changed? && twitter_id
      user = Twitter.user(self.screen_name)

      self.attributes = {
        twitter_id:        user.id,
        name:              user.name,
        location:          user.location,
        description:       user.description,
        url:               user.url,
        date_registration: user.created_at,
        lang:              user.lang,
        profile_image_url: user.profile_image_url
      }
    end
  end

end

app/controllers/admin/sources_controller.rb
class Admin::SourcesController < Admin::AdminController

  before_filter :find_source, :only => [:show, :edit, :update]

  def index
    if params['category']
      @category = Category.find(params['category'])
      @sources = @category.sources.paginate(:page => params[:page])
    else
      @sources = Source.paginate(:page => params[:page])
    end
    @categories = Category.active.order("name asc")
  end

  def show
  end

  def new
    @source = Source.new
    @categories = Category.active.order("name asc")
  end

  def create
    @source = Source.new(params[:source])
    @categories = Category.active.order("name asc")
    if @source.save
      redirect_to admin_sources_path, notice: "Source added successfully"
    else
      flash[:errors] = @source.errors.full_messages
      render :new
    end
  end

  def edit
    @categories = Category.active.order("name asc")
  end

  def update
    @categories = Category.active.order("name asc")

    if @source.update_attributes(params[:source])
      redirect_to admin_sources_path, notice: "Source updated successfully"
    else
      flash[:errors] = @source.errors.full_messages
      render :edit
    end
  end

  def destroy
    source = Source.find(params[:id])
    if source.destroy
      flash[:notice] = "Source deleted successfully"
    else
      flash[:errors] = source.errors.full_messages
    end
    redirect_to admin_sources_path
  end

  private
  def find_source
    @source = Source.find(params[:id])
  end
end

app/views/admin/sources/_form.html.erb
<%= render partial: "/admin/shared/flash_messages" %>

<%= form_for ["admin", source], html: { class: "form-horizontal" } do |f| %>
  <%= field_set_tag do %>
    <div class="control-group">
      <%= f.label :screen_name, class: "control-label" %>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">@</span><%= f.text_field :screen_name, class: "span3" %>
        </div>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :active, class: "control-label" %>
      <div class="controls">
        <label class="checkbox">
          <%= f.check_box :active %>
          Uncheck to hide this source
        </label>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :category_id, class: "control-label" %>
      <div class="controls">
        <%= collection_select :source, :category_id, categories, :id, :name, class: "span3" %>
      </div>
    </div>

    <div class="form-actions">
      <% if source.new_record? %>
        <%= f.submit "Create Source", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Update Source", class: "btn btn-primary" %>
      <% end %>
         <%= link_to "Cancel", admin_sources_path, class: "btn" %>
    </div>
  <% end %>
<% end %>

app/views/admin/sources/edit.html.erb
<div class="page-header">
  <h1>Sources &raquo; Edit</h1>
</div>

<%= render "form", :source => @source, :categories => @categories %>

app/views/admin/sources/index.html.erb
<div class="page-header">
  <h1>Sources</h1>
</div>

<%= render partial: "/admin/shared/flash_messages" %>

<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to new_admin_source_path, class: "btn btn-success" do %>
      <i class="icon-plus-sign icon-white"></i>
      New Source
    <% end %>
  </div>
  <div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      Filter by Category: <%= (@category) ? @category.name : "All" %>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><%= link_to "All", admin_sources_path %></li>
      <% @categories.each do |category| %>
        <li><%= link_to category.name, "?category="+category.id.to_s %></li>
      <% end %>
    </ul>
  </div>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th class="span1">Id</th>
    <th>Name</th>
    <th>Category</th>
    <th>Active</th>
    <th class="span3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sources.each do |s| %>
      <tr>
        <td><%= s.id %></td>
        <td><%= s.screen_name %></td>
        <td><%= s.category.name %></td>
        <td><%= yes_no_label(s.active) %></td>
        <td>
          <%= link_to admin_source_path(s.id), class: "btn btn-mini" do %>
              <i class="icon-eye-open"></i>
              View
          <% end %>
          <%= link_to edit_admin_source_path(s.id), class: "btn btn-mini" do %>
              <i class="icon-pencil"></i>
              Edit
          <% end %>
          <%= link_to admin_source_path(s.id), class: "btn btn-danger btn-mini", confirm: "Are you sure you want to delete this source?", method: :delete do %>
              <i class="icon-trash icon-white"></i>
              Delete
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="5"><%= pluralize @sources.count, "Source" %> found</td>
  </tr>
  </tfoot>
</table>

<%= will_paginate %>

app/views/admin/sources/new.html.erb
<div class="page-header">
  <h1>Sources &raquo; New</h1>
</div>

<%= render "form", :source => @source, :categories => @categories %>

app/views/admin/sources/show.html.erb
<div class="page-header">
  <h1>Sources &raquo; @<%= @source.screen_name %></h1>
</div>

<table class="table table-bordered table-striped profile-view-table">
  <tbody>
    <tr>
      <th>Category</th>
      <td><%= @source.category_name %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td>
        <%= @source.name %>
        <%= image_tag @source.profile_image_url unless @source.profile_image_url.nil? %>
      </td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @source.description %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @source.location %></td>
    </tr>
    <tr>
      <th>Url</th>
      <td><%= link_to(@source.url, @source.url) unless @source.url.nil? %></td>
    </tr>
    <tr>
      <th>Registered at</th>
      <td><%= time_ago_in_words(@source.date_registration).titleize + " ago" unless @source.date_registration.nil? %></td>
    </tr>
    <tr>
      <th>Language</th>
      <td><%= @source.lang %></td>
    </tr>
  </tbody>
</table>

<%= link_to admin_sources_path, class: "btn" do %>
  <i class="icon-arrow-left"></i>
  Back to the listing page
<% end %>