config/routes.rb
Bluebird::Application.routes.draw do
  devise_for :users

   root :to => 'home#index'

  devise_for :users

  match 'read/:category_slug' => 'home#read', :as => "read_category"

  namespace :admin do
    root :to => "dashboard#index"
    resources :categories, :only => [:new, :create, :edit, :update, :destroy, :index]
    resources :sources
    resources :articles, :only => [:edit, :update, :destroy, :index]
    resources :users, :only => [:new, :create, :edit, :update, :destroy, :index]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :active, :cover

  has_many :sources
  has_many :articles, through: :sources
  has_attached_file :cover, styles: { full: "716x1024>", thumb: "179x256>" }

  validates_presence_of :name

  scope :active, where(:active => true)

  before_save :add_slug

  private
  def add_slug
    self.slug = name.parameterize
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController

  def index
    @categories = Category.paginate(:page => params[:page], :order => "name asc")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to admin_categories_path, notice: "Category added successfully"
    else
      flash[:errors] = @category.errors.full_messages
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to admin_categories_path, notice: "Category updated successfully"
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    if category.destroy
      flash[:notice] = "Category deleted successfully"
    else
      flash[:errors] = category.errors.full_messages
    end
    redirect_to admin_categories_path
  end

end

app/views/admin/categories/_form.html.erb
<%= render partial: "/admin/shared/flash_messages" %>

<%= form_for ["admin", category], html: { class: "form-horizontal" } do |f| %>
  <%= field_set_tag do %>
    <div class="control-group">
      <%= f.label :name, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :name, class: "span3" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :cover, class: "control-label" %>
      <div class="controls">
        <%= f.file_field :cover, class: "span3" %>
        <p class="help-block">Please add an image with a dimension of 716 x 1024 pixels or higher.</p>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :active, class: "control-label" %>
      <div class="controls">
        <label class="checkbox">
          <%= f.check_box :active %>
          Uncheck to hide this category
        </label>
      </div>
    </div>

    <div class="form-actions">
      <% if category.new_record? %>
      <%= f.submit "Create Category", class: "btn btn-primary" %>
      <% else %>
      <%= f.submit "Update Category", class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Cancel", admin_categories_path, class: "btn"   %>
    </div>
  <% end %>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="page-header">
  <h1>Categories &raquo; Edit</h1>
</div>

<%= render "form", :category => @category %>

app/views/admin/categories/index.html.erb
<div class="page-header">
  <h1>Categories</h1>
</div>

<%= render partial: "/admin/shared/flash_messages" %>

<%= link_to new_admin_category_path, class: "btn btn-success" do %>
  <i class="icon-plus-sign icon-white"></i>
  New Category
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="span1">Id</th>
      <th>Name</th>
      <th>Active</th>
      <th class="span2">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @categories.each do |c| %>
    <tr>
      <td><%= c.id %></td>
      <td><%= c.name %></td>
      <td><%= yes_no_label(c.active) %></td>
      <td>
        <%= link_to edit_admin_category_path(c.id), class: "btn btn-mini" do %>
          <i class="icon-pencil"></i>
          Edit
        <% end %>
        <%= link_to admin_category_path(c.id), class: "btn btn-danger btn-mini", confirm: "Are you sure you want to delete this category?", method: :delete do %>
          <i class="icon-trash icon-white"></i>
          Delete
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4"><%= pluralize @categories.count, "Category" %> found</td>
    </tr>
  </tfoot>
</table>

<%= will_paginate %>

app/views/admin/categories/new.html.erb
<div class="page-header">
  <h1>Categories &raquo; New</h1>
</div>

<%= render "form", :category => @category %>