config/routes.rb
Bluebird::Application.routes.draw do
  devise_for :users

   root :to => 'home#index'

  devise_for :users

  match 'read/:category_slug' => 'home#read', :as => "read_category"

  namespace :admin do
    root :to => "dashboard#index"
    resources :categories, :only => [:new, :create, :edit, :update, :destroy, :index]
    resources :sources
    resources :articles, :only => [:edit, :update, :destroy, :index]
    resources :users, :only => [:new, :create, :edit, :update, :destroy, :index]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :active, :password_confirmation, :remember_me

  validates :password, presence: true, confirmation: true, if: :needs_to_validates_password?
  validates_presence_of :first_name, :last_name, :email

  def full_name
    "#{first_name} #{last_name}"
  end

  private
  def needs_to_validates_password?
    encrypted_password_changed? || new_record?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.paginate(:page => params[:page], :order => "first_name asc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path, notice: "User added successfully"
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, notice: "User updated successfully"
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])

    if user.destroy
      flash[:notice] = "User deleted successfully"
    else
      flash[:errors] = user.errors.full_messages
    end
    redirect_to admin_users_path
  end

end

app/views/admin/users/_form.html.erb
<%= render partial: "/admin/shared/flash_messages" %>

<%= form_for ["admin", user], html: { class: "form-horizontal"} do |f| %>
    <%= field_set_tag do %>
        <div class="control-group">
          <%= f.label :first_name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :first_name, class: "span3" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :last_name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :last_name, class: "span3" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :email, class: "control-label" %>
          <div class="controls">
            <%= f.email_field :email, class: "span3" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :password, class: "control-label" %>
          <div class="controls">
            <%= f.password_field :password, class: "span3" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :password_confirmation, class: "control-label" %>
          <div class="controls">
            <%= f.password_field :password_confirmation, class: "span3" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :active, class: "control-label" %>
          <div class="controls">
            <label class="checkbox">
              <%= f.check_box :active %>
              Uncheck to hide this user
            </label>
          </div>
        </div>

        <div class="form-actions">
          <% if user.new_record? %>
            <%= f.submit "Create User", class: "btn btn-primary" %>
          <% else %>
            <%= f.submit "Update User", class: "btn btn-primary" %>
          <% end %>
          <%= link_to "Cancel", admin_users_path, class: "btn" %>
        </div>
    <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Users &raquo; Edit</h1>
</div>

<%= render "form", :user => @user %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<%= render partial: "/admin/shared/flash_messages" %>

<%= link_to new_admin_user_path, class: "btn btn-success" do %>
    <i class="icon-plus-sign icon-white"></i>
    New User
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="span1">Id</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Active</th>
      <th class="span2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
        <tr>
          <td><%= u.id %></td>
          <td><%= u.first_name %></td>
          <td><%= u.last_name %></td>
          <td><%= u.email %></td>
          <td><%= yes_no_label(u.active) %></td>
          <td>
            <%= link_to edit_admin_user_path(u.id), class: "btn btn-mini" do %>
                <i class="icon-pencil"></i>
                Edit
            <% end %>
            <%= link_to admin_user_path(u.id), class: "btn btn-danger btn-mini", confirm: "Are you sure you want to delete this user?", method: :delete do %>
                <i class="icon-trash icon-white"></i>
                Delete
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="6"><%= pluralize @users.count, "User" %></td>
    </tr>
  </tfoot>
</table>

<%= will_paginate %>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>Users &raquo; New</h1>
</div>

<%= render "form", :user => @user %>