config/routes.rb
Bluebird::Application.routes.draw do
  devise_for :users

   root :to => 'home#index'

  devise_for :users

  match 'read/:category_slug' => 'home#read', :as => "read_category"

  namespace :admin do
    root :to => "dashboard#index"
    resources :categories, :only => [:new, :create, :edit, :update, :destroy, :index]
    resources :sources
    resources :articles, :only => [:edit, :update, :destroy, :index]
    resources :users, :only => [:new, :create, :edit, :update, :destroy, :index]
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TrendingMag - Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Gonzalo Robaina - Analía González">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "admin/admin", :media => "all" %>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="container">
      <img src="/assets/logo_admin.png" alt="Trending Mag" id="logo" />

      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <div class="nav-collapse">
              <% if user_signed_in? %>
              <ul class="nav">
                <li class=""><%= link_to "Dashboard", admin_root_path %></li>
                <li class=""><%= link_to "Categories", admin_categories_path %></li>
                <li class=""><%= link_to "Sources", admin_sources_path %></li>
                <li class=""><%= link_to "Articles", admin_articles_path %></li>
                <li class=""><%= link_to "Users", admin_users_path %></li>
              </ul>
              <ul class="nav pull-right">
                <li class="divider-vertical"></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.full_name %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "Edit Account", edit_admin_user_path(current_user.id) %>
                    </li>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                    </li>
                  </ul>
                </li>
              </ul>
              <% end %>
            </div><!-- /.nav-collapse -->
          </div>
        </div><!-- /navbar-inner -->
      </div>

      <%= yield %>

     <!-- Footer
      ================================================== -->
      <footer class="footer">
        <p>TrendingMag - Proyecto final de Analista Programador de Aplicaciones Web - Analía González - Gonzalo Robaina - ORT Uruguay</p>
      </footer>

    </div><!-- /container -->

    <%= javascript_include_tag "application", "bootstrap.min.js" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TrendingMag.com</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <meta name="description" content="Experimental Page Layout Inspired by Flipboard" />
  <meta name="keywords" content="flip, pages, flipboard, layout, responsive, web, web design, grid, ipad, jquery, css3, 3d, perspective, transitions, transform" />
  <meta name="author" content="" />
  <%= stylesheet_link_tag    "application", "demo", "style", :media => "all" %>
  <%= javascript_include_tag "application", "modernizr.custom.08464" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300,300italic' rel='stylesheet' type='text/css'>

  <script id="pageTmpl" type="text/x-jquery-tmpl">
    <div class="${theClass}" style="${theStyle}">
      <div class="front">
        <div class="outer">
          <div class="content" style="${theContentStyleFront}">
            <div class="inner">{{html theContentFront}}</div>
          </div>
        </div>
      </div>
      <div class="back">
        <div class="outer">
          <div class="content" style="${theContentStyleBack}">
            <div class="inner">{{html theContentBack}}</div>
          </div>
        </div>
      </div>
    </div>
  </script>

  <%= yield :head %>
  
</head>
<body>

<%= yield %>

<script type="text/javascript">
  var $container  = $( '#flip' ),
      $pages      = $container.children().hide();
  Modernizr.load({
    test: Modernizr.csstransforms3d && Modernizr.csstransitions,
    yep : ['/assets/jquery.tmpl.min.js','/assets/jquery.history.js','/assets/core.string.js','/assets/jquery.touchSwipe-1.2.5.js','/assets/jquery.flips.js'],
    nope: 'css/fallback.css',
    callback : function( url, result, key ) {
      if( url === '/assets/fallback.css' ) {
        $pages.show();
      }
      else if( url === '/assets/jquery.flips.js' ) {
        $container.flips();
      }
    }
  });
</script>

</body>
</html>